defmodule RealinvoiceCloud.Repo.Migrations.ScopeSyncClientIdsPerNode do
  use Ecto.Migration

  @tables [:customers, :items, :invoices, :invoice_lines]

  # A client id is generated by a desk, so it is only unique *within* that desk.
  # Two desks can hand out the same id for unrelated rows, and under the old
  # global unique index the second desk's row would have been rejected as a
  # duplicate of the first's. The identity of a synced row is (node, client_id).
  def change do
    for table <- @tables do
      alter table(table) do
        add :node_id, references(:nodes, on_delete: :restrict)
      end

      drop unique_index(table, [:client_id])
      create unique_index(table, [:node_id, :client_id])
    end
  end
end
